config/routes.rb
Codermatch::Application.routes.draw do

  root :to => 'pages#alt'
  post '/signup' => 'pages#signup'
  post 'users/notify' => 'users#notify'

  post '/remotable' => 'coder_searches#make_remotable'
  post '/remotable_notification' => 'coder_searches#remote_pair_notification'
  post '/both_results_remote' => 'coder_searches#both_results_remote'
  resource :coder_search
  resources :languages
  resources :levels
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  LEVELS = ['Beginner', 'Intermediate', 'Advanced']

  attr_accessible :language_id, :language, :level, :zipcode, :firstname, :lastname, :email, :name, :login, :remotable, :notify

  # Enforces presence of zip- or post-code on signup form
  # validates_presence_of :zipcode, :on => :update
  validates_length_of :zipcode, :minimum => 5, :allow_blank => false

  belongs_to :language
  def self.from_hull_user(hull_user_id)
    hull_user = Hull.get(hull_user_id)
    github_user = hull_user['identities'].select { |i| i['provider'] == 'github' }.first
    user = User.find_or_create_by_login(github_user['login'])
    # doesn't update the user's email unless it's blank - avoids hull's cache overwriting corrections to the user's email. We need to do this for the user's name as well. 
    # Can update individual column for each user by doing something like this: 
    # u = User.last, and then: u.update_column(:name, 'Burt')
    user.update_attributes({ email: hull_user['email'], name: hull_user['name'] }) if user.email.blank?
    user
  end

  geocoded_by :zipcode
  before_save :geocoder_with_maps

  acts_as_gmappable

  def geocoder_with_maps
    if self.zipcode?
      gmap_uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address=#{self.zipcode}&sensor=false")
      gmap_webpage = open(gmap_uri).read
      gmap_hash = JSON.parse(gmap_webpage)
      self.latitude = gmap_hash["results"].first["geometry"]["location"]["lat"].to_f
      self.longitude = gmap_hash["results"].first["geometry"]["location"]["lng"].to_f
    end
  end

  def gmaps4rails_address
   #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.zipcode}"
  end

  def gmaps4rails_infowindow
    # if @current_user
      # "#{self.login}"

    # end
      html = ""
      user_zipcode = User.where(login: self.login).first.zipcode
      # if @current_user.present?
        User.where(zipcode: user_zipcode).each do |u|
          html << "<h5>#{u.name}</h5>"
        end
        html
      # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @id = params[:id] #@id is not a number but the GitHub login name
    @user = User.find_by_login(params[:id])
    if @user.nil?
      record_not_found
    end
  end

  def destroy
    @user = @current_user
    @user.destroy
    session[:current_user] = nil #not sure about this code
    flash[:hull_logout] = true

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { render nothing: true, status: 200 }
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])

    respond_to do |format|
      format.json { render nothing: true, status: 200 }
    end
  end

end

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="span11 profile-container">
			<h1 id='form-header'><%= @user.name %>'s Profile</h1>
			<hr>
		  <div class="span5">
		    <h4>Repos</h4>
		    <div data-hull-widget='repos' data-hull-login='<%= @id %>'></div>
		    <!-- If you're a current user and your GitHub login name is equal to the Hull id, then you will see the delete button -->
		    	<% if @current_user && @current_user.login == @id %>
			    	<p>
				<!-- id below is when we want to switch onclick to a JS / jQuery file -->
							<%= link_to user_path(@current_user), :method => :delete, :confirm => 'Are you sure you want to delete your account?', :class => 'btn btn-small delete' do %>
								<i class="icon-trash icon-large"></i>
								Delete my account
							<% end %>

							<!-- OLD CODE:
							<a href="#" class="btn btn-small delete" id="delete-account" onclick="Hull.logout().then(function () {window.location = '/'});destroyUser(<%=@current_user.id%>)"></a>
							 -->
						</p>
			  		<% if @current_user.notify == true %>
			  		<p>
			  			<a href="#" class="btn btn-small delete" id="delete-account" onclick="setNotifyFalse(<%=@current_user.id%>)">
								<i class="icon-envelope-alt icon-large"></i>
								Turn off remote pairing notifications
							</a>
			  		</p>
			  		<% end %>
		  		<% end %>
		  </div>
		  <div class="span5">
		    <h4>Wall</h4>
		    <div data-hull-widget='comments@hull' data-hull-uid='user/<%= @id %>'></div>
		  </div>
		</div>
	</div>
</div>